# Generated by Django 2.2.3 on 2019-07-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolist',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='dolist',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
