# Generated by Django 2.2.3 on 2019-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0002_auto_20190715_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DoList',
        ),
    ]
